# Generated by Django 5.0.6 on 2025-07-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_administrador_clienteb2b_clienteb2c_compracliente_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='Producto',
        ),
    ]
